#%RAML 1.0 DocumentationItem
  title: Change History
  content: |

        | In Version | Change Date | Who | Description |
        | --------| ----------- | --- | ----------- |
        | 0.9 | 20160614 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Individual prev and next replaced by LinkBlock, to be in line with the proposed Digital Delta 1.9 changes. |
        | 0.9 | 20160614 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Errors block replaced by the Problem block, to be in line with the proposed Digital Delta 1.9 changes. |
        | 0.9 | 20160614 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | minPageSize added. |
        | 0.9 | 20160618 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Added documentation section on error handling. |
        | 0.9 | 20160618 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Replaced FilterResponseList with Filter[]. |
        | 0.9 | 20160614 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Changed samples to reflect the correct casing in parameter names: lower case. |
        | 0.9 | 20160618 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Moved examples to separate files. |
        | 0.9 | 20160618 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Moved documentation to separate files. |
        | 0.9 | 20160619 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Split into Minimal and Extended levels. |
        | 0.9 | 20160619 | [Geri Wolters](mailto:geri.wolters@ecosys.nl) ([EcoSys](https://www.ecosys.nl)) | Modularized. |
