#%RAML 1.0 DocumentationItem
title: Extended level
content: |
    The Extended level resides on top of the Minimal level. Its purpose is to allow discovery of query parameters.
    All end-points are optional.
