#%RAML 1.0 DocumentationItem
title: Introduction
content: |
    This document is a proposal for an extension to the Digital Delta API, specifically for parameter-based queries, as opposed to the time-series focussed approach that the original DD API used.
    The document describes the required parts ('Minimal' level) and optional (discovery) parts ('Extended' level).

    Providers can use the definition to implement their own connector for this specification.
    Consumers can use the definition to connect external systems to their own systems.
    The samples given are based from an implementation of the Extended-level API for the AquaDesk system.

    Minimal level is required: the Extended level enhances this. All Extended level end-points are optional.

    
